// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVSWEuGolyYfwV9Wkef8MoBgDjAzGak0',
    appId: '1:488277519731:web:ba8e8da8a6c89b2208a906',
    messagingSenderId: '488277519731',
    projectId: 'reddit-clone-51a09',
    authDomain: 'reddit-clone-51a09.firebaseapp.com',
    storageBucket: 'reddit-clone-51a09.appspot.com',
    measurementId: 'G-7TQMTYBLJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvS9g5ffywPn5yXTU2Xz6r8uK3Wgay7wE',
    appId: '1:488277519731:android:865858f29350c6a608a906',
    messagingSenderId: '488277519731',
    projectId: 'reddit-clone-51a09',
    storageBucket: 'reddit-clone-51a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1mu1nCr4KsOZK2O2hNgwQL4yIdcRBr0',
    appId: '1:488277519731:ios:3c723b39dedafa2508a906',
    messagingSenderId: '488277519731',
    projectId: 'reddit-clone-51a09',
    storageBucket: 'reddit-clone-51a09.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU1mu1nCr4KsOZK2O2hNgwQL4yIdcRBr0',
    appId: '1:488277519731:ios:3a015503659e949008a906',
    messagingSenderId: '488277519731',
    projectId: 'reddit-clone-51a09',
    storageBucket: 'reddit-clone-51a09.appspot.com',
    iosBundleId: 'com.example.redditTutorial.RunnerTests',
  );
}
